# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Html',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'tbl_html',
            },
        ),
        migrations.CreateModel(
            name='MasterTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img_path', models.CharField(max_length=255)),
                ('html_path', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_master',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
                ('content', models.TextField(default='')),
                ('added', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_module',
            },
        ),
    ]
