# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_theme',
            },
        ),
    ]
