# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_builder', '0002_module_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_builder.MasterTemplate'),
        ),
    ]
